cache = 'CACHE', '\n', FILE_NAME, *('\n', FILE_NAME)
decache = 'DECACHE', '\n', FILE_NAME, *('\n', FILE_NAME)
call = 'CALL', '\n', AGENT_NAME, '\n', *(UTF8)
return = 'RETURN', '\n', *(UTF8)
yield = 'YIELD', '\n', SHELL_COMMAND
log = 'LOG', '\n', *(UTF8)